version: "latest"

services:
  pg-docker:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reactmvp_db
    ports:
      - 6432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
   
volumes:
    pg-data: